name: firebase_image
description: Firebase storage photo image provider for images, gifs and videos.
version: 0.0.3
author: Roland Volskaya
homepage: github.com/volskaya/firebase_image
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.0.0-nullsafety.1
  path_provider: ^2.0.1
  quiver: ^3.0.0
  firebase_storage: ^8.0.0
  mobx: ^2.0.0-nullsafety.5
  flutter_mobx: ^2.0.0-nullsafety.3
  mobx_codegen: ^2.0.0-nullsafety.2
  json_annotation: ^4.0.1
  provider: ^5.0.0
  freezed_annotation: ^0.14.1

  await_route:
    path: /home/projects/packages/flutter_helpers/await_route
  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  firestore_model:
    path: /home/projects/packages/firestore_model
  log:
    path: /home/projects/packages/flutter_helpers/log

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

dev_dependencies:
  build_runner:
  json_serializable: ^4.1.0
  freezed: ^0.14.1+1

flutter:
