name: firebase_image
description: Firebase storage photo image provider for images, gifs and videos.
version: 0.0.3
author: Roland Volskaya
homepage: github.com/volskaya/firebase_image

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.4.1
  path_provider: ^1.6.11
  quiver: ^2.1.3
  firebase_storage: ^4.0.0
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  mobx_codegen:
  json_annotation: ^3.0.1

  await_route:
    git:
      url: git@github.com:volskaya/flutter_helpers.git
      path: await_route
  fancy_switcher:
    git:
      url: git@github.com:volskaya/fancy_switcher.git
  firestore_model:
    git:
      url: git@github.com:volskaya/firestore_model.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

dependency_overrides:
  analyzer: '0.39.14'

flutter:
