name: firebase_image
description: Firebase storage photo image provider for images, gifs and videos.
version: 0.0.3
author: Roland Volskaya
homepage: github.com/volskaya/firebase_image

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.4.1
  path_provider: ^1.6.11
  quiver: ^2.1.3
  firebase_storage: ^4.0.0
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  mobx_codegen:
  json_annotation: ^3.0.1
  provider: ^4.3.2+2
  freezed_annotation: ^0.12.0

  await_route:
    path: /home/projects/packages/flutter_helpers/await_route
  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  firestore_model:
    path: /home/projects/packages/firestore_model
  log:
    path: /home/projects/packages/flutter_helpers/log

dependency_overrides:
  # Conditionally checks if an observable should update.
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed: ^0.12.6

flutter:
